#!/usr/bin/env ruby
require 'fileutils'
include FileUtils

APP_ROOT = File.expand_path('..', __dir__)

chdir APP_ROOT do
  system %(DISABLE_SPRING=1 SPEC_COVERAGE=1 bin/rails spec)
  system %(open coverage/index.html; true)
end